apiVersion: serving.mlspec.org/v1alpha2
kind: MLGraph
metadata:
  name: ensemble
spec:
  dag:
    - name: a
      implementation:
        kfservice:
          spec:
            default:
              sklearn:
                modelUri: "gs://kfserving-samples/models/sklearn/iris/"          
    - name: b
      implementation:
        kfservice:
          spec:
            default:
              xgboost:
                modelUri: "gs://kfserving-samples/models/xgboost/iris/"
    - name: c
      implementation:
        kfservice:
          spec:
            default:
              tensorflow:
                modelUri: "gs://kfserving-samples/models/tensorflow/iris/"
    - name: d
      dependencies: [a, b, c]
      merge:
        ensemble:
