apiVersion: serving.mlspec.org/v1alpha2
kind: MLGraph
metadata:
  name: ensemble
  namespace: test
spec:
  dag:
    - name: a
      implementation:
        ref:
          kfservice: sklearnModel
    - name: b
      implementation:
        ref:
          kfservice: xgboostModel
    - name: ensemble
      dependencies: [a, b]
      merge:
        ensemble:
  analysis:    
    explanation:
    outliers:
    skew:
    bias:
    reporting:
      ref:
        apiVersion: eventing.knative.dev/v1alpha1
        kind: Channel
        name: mlgraph_alerts
      
