apiVersion: serving.mlspec.org/v1alpha2
kind: MLGraph
metadata:
  name: mab_kf
  namespace: test
spec:
  dag:
    - name: mab
      route:
        mab:
          egreedy: 0.1
    - name: a
      dependencies: [mab]
      implementation:
        inline:
          kfspec:
            default:
              sklearn:
                modelUri: "gs://kfserving-samples/models/sklearn/iris/"
    - name: b
      dependencies: [mab]
      implementation:
        inline:
          kfspec:
            default:
              xgboost:
                modelUri: "gs://kfserving-samples/models/xgboost/iris/"
