apiVersion: serving.mlspec.org/v1alpha2
kind: MLGraph
metadata:
  name: ensemble
  namespace: test
spec:
  dag:
    - name: route
      route:
        mab:
          egreedy: 0.1    
    - name: modelA
      dependencies: [route]
      implementation:
        ref:
          kfservice: sklearnModel
    - name: modelB
      dependencies: [route]      
      implementation:
        inline:
          kfspec:
            default:
              xgboost:
                modelUri: "gs://kfserving-samples/models/xgboost/iris/"
    - name: transform
      dependencies: [route]
      implementation:
        inline:
          podspec:
            containers:
                image: myorg/transformer:0.1
    - name: modelC
      dependencies: [transform]
      implementation:
        ref:
          uri: http://external.org/model
    - name: join
      dependencies: [modelA, modelB, modelC]
      merge:
        ensemble:
